apiVersion: 1
datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    isDefault: true
    editable: true
    url: http://influxdb:8086
    secureJsonData:
      token: ultra_secret_token
    jsonData:
      version: Flux
      organization: btam-org
      defaultBucket: btam-bucket